<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php if($block->isEnabled()):?>
	<?php foreach ($block->getTypePersonOptions() as $opt): ?>
        <div class="">
            <div class="field typeperson required">
            	<label class="label" for="typeperson<?php echo $block->escapeHtml($opt->getValue()) ?>">
            		<span>
            			<?php /* @escapeNotVerified */ echo $opt->getLabel() ?>
        			</span>
        		</label>    
                <div class="control">
                    <input 
                    type="radio" 
                    id="typeperson<?php echo $block->escapeHtml($opt->getValue()) ?>" 
                    name="<?php /* @escapeNotVerified */ echo $block->getFieldName('typeperson')?>" 
                    value="<?php echo $block->escapeHtml($opt->getValue()) ?>" 
                    title="<?php /* @escapeNotVerified */ echo $opt->getLabel() ?>"
                    <?php echo $block->escapeHtml($opt->getValue() == '2') ? 'checked' : '' ?>
                    class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('typeperson') ?>" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?> data-validate="{required:true}" >
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>