<?php 

    $_helper  = $this->helper('\Jbp\Customer\Helper\Data');

?>
<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>

<div class="container">
	<div class="row">

            <?php echo $block->getChildHtml('form_fields_before')?>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.register.extra')?>
            <form class="form create account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
                
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 reset-padding">
                    <fieldset class="fieldset create info">
                        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Personal Information') ?></span></legend><br>
                        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
                        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
						
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 reset-padding">
							<?php 
							     echo  $block->getLayout()->createBlock('Jbp\Customer\Block\Widget\Person')->toHtml(); 
							?>
						</div>
						
                    	<?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                        
                        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                        <?php if ($_dob->isEnabled()): ?>
                        	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            	<?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                        	</div>
                        <?php endif ?>
                        
                        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                        <?php if ($_gender->isEnabled()): ?>
                        	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            	<?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                        	</div>
                        <?php endif ?>
                
                        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                        <?php if ($_taxvat->isEnabled()): ?>                        	
                        	<?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>                            
                        <?php endif ?>
                        
                        <?php if ($block->isNewsletterEnabled()): ?>
                        	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="field choice newsletter">
                                    <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                                    <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
                                </div>
                                <?php /* Extensions placeholder */ ?>
                                <?php echo $block->getChildHtml('customer.form.register.newsletter')?>
                            </div>
                        <?php endif ?>
                        
                    </fieldset>
                </div>
                
                
                <?php if ($block->getShowAddressFields()): ?>
                	<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <fieldset class="fieldset address">
                            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend><br>
                            <input type="hidden" name="create_address" value="1" />
                
                            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
                
                            <div class="field zip required col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="control">
                                    <input 
                                     type="text" 
                                     placeholder="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>"
                                     name="postcode" 
                                     value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" 
                                     title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" 
                                     id="zip" 
                                     onpaste="return false;"
                                     onCopy="return false"
                                     onDrag="return false"
                                     autocomplete=off
                                     class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                                </div>
                            </div>
                			
                            <div class="field street required">
                                
                                <div class="control">
                                	                                	
                                    <div class="nested">
                                    	
                                    	<div class="field required col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                    		<div class="control">
                                            	<input 
                                            	type="text" 
                                            	placeholder="<?php echo $_helper->getLabelAddressByRow(1); ?>" 
                                            	name="street[]" 
                                            	value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" 
                                            	title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" 
                                            	id="street_1" 
                                            	class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                        	</div>
    									</div>
    									
                                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                            <div class="field required col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                                <div class="control">
                                                	<input 
                                                	 type="text"
                                                	 placeholder="<?php echo $_helper->getLabelAddressByRow($_i); ?>" 
                                                	 name="street[]"
                                                	 value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" 
                                                	 title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" 
                                                	 id="street_<?php /* @escapeNotVerified */ echo $_i ?>"
                                                	 class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>" 
                                                	 data-validate="{required:true}"
                                                	 >
                                                </div>
                                            </div>
                                        <?php endfor; ?>
                                        
                                    </div>
                                    
                                </div>
                                
                            </div>
                
                            <div class="field required col-lg-6 col-md-6 col-sm-12 col-xs-12">                                
                                <div class="control">
                                    <input type="text" placeholder="<?php /* @escapeNotVerified */ echo __('City') ?>" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                                </div>
                            </div>
                
                            <div class="field region required col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="control">
                                    <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                                        <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                                    </select>
                                    <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                                </div>
                            </div>

                            <div class="field country required hide">
                                <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                                <div class="control">
                                    <?php echo $block->getCountryHtmlSelect() ?>
                                </div>
                            </div>
                            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                            <?php if ($addressAttributes): ?>
                                <?php $addressAttributes->setEntityType('customer_address'); ?>
                                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                                <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
                            <?php endif;?>
                            <input type="hidden" name="default_billing" value="1">
                            <input type="hidden" name="default_shipping" value="1">
                        </fieldset>
            		</div>
                <?php endif; ?>
                
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                        
                        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Sign-in Information') ?></span></legend><br>
                        
                        <div class="field required col-lg-4 col-md-4 col-sm-12 col-xs-12">
                            <div class="control">
                                <input type="email" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>" name="email" autocomplete="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        
                        <div class="field password required col-lg-3 col-md-3 col-sm-12 col-xs-12" data-mage-init='{"passwordStrengthIndicator": {}}'>
                            
                            <div class="control">
                                <input type="password" name="password" id="password"
                                       title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                                       class="input-text"
                                       placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                                       data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                                       data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                                       data-validate="{required:true, 'validate-customer-password':true}"
                                       autocomplete="off">
                                <div id="password-strength-meter-container" data-role="password-strength-meter" >
                                    <div id="password-strength-meter" class="password-strength-meter">
                                        <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                                        <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                                            <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                                        </span>
                                    </div>
                                </div>
                            </div>                
                        </div>
                        
                        <div class="field confirmation required col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <div class="control">
                                <input type="password" name="password_confirmation" placeholder="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                            </div>
                        </div>
                        
                        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                        	<div class="actions-toolbar pull-right">
                                <div class="primary">
                                    <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>
                                </div>
                                <div class="secondary">
                                    <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
                                </div>
                            </div>
                        </div>
                        
                        <?php echo $block->getChildHtml('form_additional_info'); ?>
                        
                    </fieldset>
                </div>
            
            </form>

	</div>
</div>

<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;
    
    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>
